name: DNAseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - bioconductor-biobase=2.50.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-biocparallel=1.24.0
  - bioconductor-biostrings=2.58.0
  - bioconductor-delayedarray=0.16.0
  - bioconductor-genomeinfodb=1.26.0
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicalignments=1.26.0
  - bioconductor-genomicranges=1.42.0
  - bioconductor-iranges=2.24.0
  - bioconductor-matrixgenerics=1.2.0
  - bioconductor-noiseq=2.34.0
  - bioconductor-rhtslib=1.22.0
  - bioconductor-rsamtools=2.6.0
  - bioconductor-rtracklayer=1.50.0
  - bioconductor-s4vectors=0.28.0
  - bioconductor-summarizedexperiment=1.20.0
  - bioconductor-xvector=0.30.0
  - bioconductor-zlibbioc=1.36.0
  - bowtie2=2.3.4.2
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - curl=7.75.0
  - cutadapt=3.3
  - dataclasses=0.7
  - dnaio=0.5.0
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.3.0
  - gfortran_linux-64=9.3.0
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - harfbuzz=2.7.4
  - htslib=1.11
  - icu=68.1
  - isa-l=2.30.0
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.17.2
  - ld_impl_linux-64=2.35.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.75.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - make=4.3
  - ncurses=6.2
  - openjdk=11.0.1
  - openssl=1.1.1j
  - pango=1.42.4
  - pcre=8.44
  - pcre2=10.36
  - perl=5.32.0
  - pigz=2.5
  - pip=21.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.6.13
  - python-isal=0.5.0
  - python_abi=3.6
  - qualimap=2.2.2d
  - r-base=4.0.3
  - r-bh=1.75.0_0
  - r-bitops=1.0_6
  - r-crayon=1.4.1
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.3
  - r-lambda.r=1.2.4
  - r-lattice=0.20_41
  - r-matrix=1.3_2
  - r-matrixstats=0.58.0
  - r-optparse=1.6.6
  - r-rcurl=1.98_1.2
  - r-snow=0.4_3
  - r-xml=3.99_0.5
  - readline=8.0
  - samtools=1.11
  - sed=4.8
  - setuptools=49.6.0
  - sqlite=3.34.0
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - wheel=0.36.2
  - xopen=1.1.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
